---
- name: Clone a microservice repo
  hosts: localhost
  vars:
    repo: https://github.com/pipeline-testing/microservice.git
    Port: 8086

  tasks:

      - name: Run clone-repo role to clone the gradle application
        include_role:
          name:  clone-repo
          
      - name: Run set-port role to change the application-properties
        include_role:
          name:  set-port          
